/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author brun
 */
public class Applet extends java.applet.Applet {

    /**
     * Initializes the applet Applet
     */
    public void init() {
        try {
            java.awt.EventQueue.invokeAndWait(new Runnable() {
                public void run() {
                    initComponents();
                }
            });
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the init() method to initialize the
     * form. WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Salida = new javax.swing.JTextArea();

        setForeground(new java.awt.Color(10, 3, 3));
        setLayout(new java.awt.BorderLayout());

        jLabel1.setForeground(new java.awt.Color(44, 44, 44));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Applet");
        jLabel1.setToolTipText("");
        add(jLabel1, java.awt.BorderLayout.CENTER);

        jButton1.setText("Presionar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        add(jButton1, java.awt.BorderLayout.SOUTH);

        jScrollPane1.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane1.setForeground(new java.awt.Color(44, 44, 44));

        Salida.setBackground(new java.awt.Color(255, 255, 255));
        Salida.setColumns(20);
        Salida.setForeground(new java.awt.Color(247, 58, 13));
        Salida.setRows(5);
        jScrollPane1.setViewportView(Salida);

        add(jScrollPane1, java.awt.BorderLayout.WEST);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        String sal="El boton ha sido presionado";
        Salida.setText(sal);
                ;
    }//GEN-LAST:event_jButton1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Salida;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
